### ISSUE TITLE
ENOENT: no such file or directory, open 'dist/.clasp.json' (npm run create-clasp-project)

### ISSUE THREAD

**Issue by mitchhankins01** [thinkle/Google-Apps-Script-Svelte-Starter#1]
Hi Tom,

I love this project you have put together!

I was able to get the project running locally, but when trying to run the instructions in the README in order to deploy, the final command results in an error.

npm install
npm run dev
npm run build
npm run create-clasp-project

I get:
ENOENT: no such file or directory, open 'dist/.clasp.json'

I've looked trough the README and package.json, and I am not seeing instructions on how to resolve. Perhaps I should set the "scriptId" property on line 5 of createClaspProject.js?

**Comment by mitchhankins01** [comment]
Fixed this by changing 
npx clasp create --title "${projectName}" --type standalone --rootDir dist/

to

mkdir dist && npx clasp create --title "${projectName}" --type standalone --rootDir dist/

I tried to submit a PR but did not have permissions.

**Comment by thinkle** [comment]
Thanks for the fix -- sorry I missed this!
